# Generated by Django 5.0.1 on 2024-04-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffee',
            new_name='food',
        ),
    ]
