# Generated by Django 5.0.1 on 2024-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_sharingfood_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingfood',
            name='foodtype',
            field=models.CharField(blank=True, choices=[('RAW', 'Raw'), ('COOKED', 'Cooked'), ('PACKED', 'Packed')], default='COOKED', max_length=9, null=True),
        ),
    ]
