# Generated by Django 5.0.1 on 2024-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_sharingfood_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingfood',
            name='foodtype',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Cooked', 'Cooked'), ('Packed', 'Packed')], max_length=9, null=True),
        ),
    ]
