# Generated by Django 5.0.1 on 2024-05-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_sharingfood_foodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingfood',
            name='foodtype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
